[project]
name = "protolstm-weight-adjustment"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "flax>=0.10.5",
    "optax>=0.2.4",
    "safetensors>=0.5.3",
    "tf-nightly>=2.20.0.dev20250413",
]

[project.optional-dependencies]
nb = [
    "marimo>=0.12.10",
]
